### PR TITLE
drop `--as-needed` linker option on MacOS

### LINKED ISSUE #2: MacOS linker doesn't support --as-needed option
Which is used here https://github.com/janestreet/jenga-rules/blob/master/lib/root.ml#L3724

```
(match Mode.which with
           | `Native -> ["-ccopt"; "-Wl,--as-needed"]
           | `Byte -> ["-custom"]);
```

Thus trying to build a project with `jane-build` fails with `ld: unknown option: --as-needed`

I understand that jenga-rules are Jenga rules used at Jane Street and they are not to be adapted for everyone's needs, but probably fixing that particular issue would be not very intrusive change.

### PR DESCRIPTION
**Pull request by ul**
fix #2

### CODE REVIEW

**Comment by thedufer** [comment]
Does this allow you to build on OS X?  I see warnings like (one for each library):

    ignoring file ../.liblinks/<lib>/<lib>.a, file was built for archive which is not the architecture being linked (x86_64): ../.liblinks/<lib>/<lib>.a

And then some undefined symbol errors clearly related to the ignored files.  Searching indicates that this might be related to using the wrong `gar` (GNU ar).  I installed that via `brew install binutils`; perhaps you are using something different?

**Comment by ul** [comment]
I'm using gcc and stuff from XCode. You need to install XCode and then perform `$ xcode-select --install` to install its command line tools.

**Comment by thedufer** [comment]
`jane-build` expects a `gar` executable (conditional on uname "Darwin"; otherwise it uses `ar`), which is not (as far as I can tell) installed with the xcode command-line tools.  Any idea where you got `gar` from?

**Comment by ul** [comment]
Strange, I have no `gar`, but have `ar`, and my project compiles fine with `jane-build` on MacOS 10.12.3

**Comment by hhugo** [comment]
Jenga-rules is no longer supported

**Pull request closed without merging**
